// =============================================================================
// page-fields - the registry, and the DRIFT GATE that keeps it honest
// =============================================================================
// src/lib/page-fields.ts duplicates knowledge that lives in the schema, because
// the preview island cannot ask the Studio which fields a page has. The
// duplication is only safe while something checks it, so this file reads THREE
// sources and fails when they and the registry disagree:
//
//   - schema.json, the EXTRACTED schema, for which page type declares each
//     line. Reading the extracted schema rather than the .ts sources is a
//     deliberate difference from mas-monograms' copy of this gate: eleven of
//     this site's page singletons are built by a FACTORY
//     (src/sanity/schemaTypes/churchPages.ts), so there is no per-type source
//     file to parse and a regex over the factory would answer for all eleven at
//     once. schema.json is what the Studio actually registers.
//   - src/sanity/urls.ts, for which singletons the site treats as previewable.
//   - src/pages/preview/[...slug].astro, for whether the preview surface really
//     renders the line. A card can only hang on an element that exists, and
//     "the schema has the field" is not "the editor sees it".
//
// schema.json is generated by `npm run typegen` and gitignored, so the schema
// half SKIPS when it is absent and RUNS in CI, where typegen is the step before
// the tests. A skipped gate says so in the output rather than passing silently.
// =============================================================================
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import {
  EDITABLE_LINES,
  PAGE_TYPES,
  cleanLine,
  overlayControlsForPath,
  resolveTextTarget,
} from './page-fields.ts';

const path = (relative: string) => fileURLToPath(new URL(relative, import.meta.url));
const read = (relative: string) => readFileSync(path(relative), 'utf8');

const PREVIEW_ROUTE = read('../pages/preview/[...slug].astro');
const URLS = read('../sanity/urls.ts');

const SCHEMA_PATH = path('../../schema.json');
const HAVE_SCHEMA = existsSync(SCHEMA_PATH);

interface SchemaDoc {
  name: string;
  type: string;
  attributes?: Record<string, { value?: { type?: string } }>;
}

const SCHEMA: SchemaDoc[] = HAVE_SCHEMA ? JSON.parse(readFileSync(SCHEMA_PATH, 'utf8')) : [];

/** The document types that declare `field` as a plain string or text field. */
function typesDeclaring(field: string): string[] {
  return SCHEMA.filter((doc) => {
    if (doc.type !== 'document') return false;
    const attr = doc.attributes?.[field];
    const t = attr?.value?.type;
    return t === 'string' || t === 'text';
  }).map((doc) => doc.name);
}

// Sanity's stega payload is a run of invisible characters appended to a string.
const STEGA_TAIL = '​‌‍﻿​‌';
const encoded = (text: string) => text + STEGA_TAIL;

// =============================================================================
// The drift gate
// =============================================================================

test('PAGE_TYPES matches the previewable singletons, plus the generic page type', () => {
  // src/sanity/urls.ts is the one page map; the registry must not know about a
  // page the preview cannot serve, or miss one it can.
  const listed = [...URLS.matchAll(/\{ type: '(\w+)', path:/g)].map((m) => m[1]);
  assert.ok(listed.length > 0, 'could not parse SINGLETON_PAGES out of src/sanity/urls.ts');
  assert.deepEqual([...PAGE_TYPES], [...listed, 'page']);
});

test('every line in the registry is declared by exactly the types it claims', (t) => {
  if (!HAVE_SCHEMA) {
    t.skip('schema.json not found - run `npm run typegen` (CI always has it)');
    return;
  }
  for (const line of EDITABLE_LINES) {
    // Restricted to PAGE_TYPES: `title` is declared by half the collections too,
    // and this layer only ever sees a page document.
    const declaring = typesDeclaring(line.name).filter((name) => PAGE_TYPES.includes(name));
    assert.deepEqual(
      [...line.onTypes].sort(),
      declaring.sort(),
      `${line.name}: onTypes does not match the schemas that declare it`,
    );
  }
});

test('every line in the registry is one the preview surface renders', () => {
  // The preview route reads each of these off the document. A line the route
  // stopped rendering would leave a card with no element to hang on.
  for (const line of EDITABLE_LINES) {
    assert.ok(
      PREVIEW_ROUTE.includes(`doc.${line.name}`),
      `${line.name}: the preview route does not render it`,
    );
  }
});

test('the seo fields are deliberately absent: the preview draws no <head>', (t) => {
  if (!HAVE_SCHEMA) {
    t.skip('schema.json not found');
    return;
  }
  // seoTitle and seoDescription are on every page, and the preview shell writes
  // its own <title>. There is no element on the page to point a card at.
  assert.ok(typesDeclaring('seoTitle').length > 0, 'seoTitle has gone from the schemas');
  assert.equal(overlayControlsForPath('seoTitle').length, 0);
  assert.equal(overlayControlsForPath('seoDescription').length, 0);
});

test('heroScriptAccent gets no card yet, and that is a decision', (t) => {
  if (!HAVE_SCHEMA) {
    t.skip('schema.json not found');
    return;
  }
  // The field is real and Hero renders it, unlike on mas-monograms where the
  // equivalent had nothing behind it. It is absent here because the pick-a-word
  // picker is a separate card (the inline-rich write path comes with it), not
  // because nothing can use it. Delete this test on the day the picker lands.
  assert.ok(
    typesDeclaring('heroScriptAccent').length > 0,
    'heroScriptAccent has gone from the schemas; drop this test',
  );
  assert.equal(overlayControlsForPath('heroScriptAccent').length, 0);
});

// =============================================================================
// The lookups
// =============================================================================

test('overlayControlsForPath offers the text card on a registry field', () => {
  assert.deepEqual(overlayControlsForPath('heroHeadline'), ['text']);
  assert.deepEqual(overlayControlsForPath('heroSubhead'), ['text']);
  assert.deepEqual(overlayControlsForPath('heroKeyword'), ['text']);
});

test('overlayControlsForPath leaves everything else to the host overlay', () => {
  assert.deepEqual(overlayControlsForPath('seoTitle'), []);
  assert.deepEqual(overlayControlsForPath('heroImages'), []);
  assert.deepEqual(overlayControlsForPath('flexibleSections[_key=="a"].heading'), []);
  assert.deepEqual(overlayControlsForPath('hero.heroHeadline'), []);
  assert.deepEqual(overlayControlsForPath(''), []);
  assert.deepEqual(overlayControlsForPath(undefined), []);
});

test('never offers two controls on one element, which would stack them', () => {
  for (const line of EDITABLE_LINES) {
    assert.equal(overlayControlsForPath(line.name).length, 1);
  }
});

test('resolveTextTarget points the card at the field and seeds it', () => {
  const doc = { _type: 'homePage', heroHeadline: 'A church in the heart of the city' };
  assert.deepEqual(resolveTextTarget(doc, 'heroHeadline'), {
    path: ['heroHeadline'],
    text: 'A church in the heart of the city',
    label: 'Headline',
    rows: 2,
  });
});

test('resolveTextTarget refuses a field the document type does not declare', () => {
  // `headline` belongs to the 404 page. Offering it on the home page would
  // write a value into a document whose form has no box for it.
  assert.equal(resolveTextTarget({ _type: 'homePage', headline: 'x' }, 'headline'), null);
  assert.ok(resolveTextTarget({ _type: 'notFoundPage', headline: 'x' }, 'headline'));
});

test('resolveTextTarget strips the stega payload before it reaches the box', () => {
  const target = resolveTextTarget(
    { _type: 'homePage', heroHeadline: encoded('Welcome home') },
    'heroHeadline',
  );
  assert.equal(target?.text, 'Welcome home');
});

test('cleanLine survives a non-string', () => {
  assert.equal(cleanLine(undefined), '');
  assert.equal(cleanLine(42), '');
  assert.equal(cleanLine(encoded(' Sunday worship ')), 'Sunday worship');
});
