/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Sermon = {
  _id: string;
  _type: "sermon";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  date?: string;
  speaker?: string;
  series?: string;
  scripture?: string;
  videoUrl?: string;
  audioUrl?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h3";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  featured?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  eventType?: "recurring" | "oneTime";
  category?:
    | "Worship"
    | "Study"
    | "Meals"
    | "Music"
    | "Fellowship"
    | "Service"
    | "Special";
  scheduleLabel?: string;
  start?: string;
  end?: string;
  location?: string;
  summary?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h3";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  registrationUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  featured?: boolean;
};

export type JournalCategory = {
  _id: string;
  _type: "journalCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type PhilosophyPoint = {
  _id: string;
  _type: "philosophyPoint";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  displayOrder?: number;
  orderRank?: string;
};

export type FaqItem = {
  _id: string;
  _type: "faqItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h4";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  category?:
    | "Pricing & Cost"
    | "The Process"
    | "Logistics"
    | "Service Area"
    | "Getting Started";
  displayOrder?: number;
  alsoShowOnProcessPage?: boolean;
};

export type StudioPlaybook = {
  _id: string;
  _type: "studioPlaybook";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  intro?: string;
  guides?: Array<{
    title?: string;
    summary?: string;
    sections?: Array<{
      heading?: string;
      tone?: "default" | "primary" | "positive" | "caution";
      body?: string;
      bullets?: Array<string>;
      links?: Array<{
        label?: string;
        url?: string;
        _type: "playbookLink";
        _key: string;
      }>;
      _type: "playbookSection";
      _key: string;
    }>;
    _type: "playbookGuide";
    _key: string;
  }>;
};

export type StudioNotes = {
  _id: string;
  _type: "studioNotes";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  businessSummary?: string;
  idealClient?: string;
  voiceSummary?: string;
  wordsToAvoid?: Array<string>;
};

export type StudioGuide = {
  _id: string;
  _type: "studioGuide";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  guideTitle?: string;
  guideIntro?: string;
  studioMap?: Array<{
    area?: string;
    description?: string;
    _type: "mapRow";
    _key: string;
  }>;
  howTos?: Array<{
    title?: string;
    steps?: Array<string>;
    _type: "howTo";
    _key: string;
  }>;
  tips?: Array<{
    heading?: string;
    tone?: "default" | "primary" | "caution" | "positive";
    body?: string;
    _type: "tip";
    _key: string;
  }>;
};

export type PrivacyPage = {
  _id: string;
  _type: "privacyPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroScriptAccent?: string;
  lastUpdated?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type NotFoundPage = {
  _id: string;
  _type: "notFoundPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  eyebrow?: string;
  headline?: string;
  body?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
  };
  primaryCtaLabel?: string;
  primaryCtaHref?: string;
  secondaryCtaLabel?: string;
  secondaryCtaHref?: string;
  tertiaryCtaLabel?: string;
  tertiaryCtaHref?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  tagline?: string;
  email?: string;
  phone?: string;
  availabilityStatus?: string;
  serviceAreas?: Array<string>;
  travelFees?: Array<{
    distanceLabel?: string;
    fee?: string;
    _type: "travelFeeTier";
    _key: string;
  }>;
  socialInstagram?: string;
  socialFacebook?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  footerCredit?: string;
  footerCreditUrl?: string;
  newsletter?: {
    enabled?: boolean;
    providerLabel?: string;
    formActionUrl?: string;
    audienceId?: string;
    heading?: string;
    blurb?: string;
    buttonLabel?: string;
    successMessage?: string;
    consentNote?: string;
  };
  googleBusinessUrl?: string;
  reviewsNote?: string;
  sectionVisibility?: {
    showPortfolio?: boolean;
    showJournal?: boolean;
    showShop?: boolean;
    showEDesign?: boolean;
    showGiftCertificates?: boolean;
    showPress?: boolean;
    showResources?: boolean;
    showGuides?: boolean;
    showStyleQuiz?: boolean;
    showBudgetCalculator?: boolean;
  };
  satisfactionGuarantee?: string;
};

export type HomePageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "homePage";
};

export type AboutPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "aboutPage";
};

export type FaqPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "faqPage";
};

export type ContactPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "contactPage";
};

export type JournalPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "journalPage";
};

export type EventsPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "eventsPage";
};

export type SermonsPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sermonsPage";
};

export type JournalEntryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "journalEntry";
};

export type CtaBlock = {
  _type: "ctaBlock";
  label?: string;
  linkType?: "internal" | "external" | "email" | "phone";
  internalLink?:
    | HomePageReference
    | AboutPageReference
    | FaqPageReference
    | ContactPageReference
    | JournalPageReference
    | EventsPageReference
    | SermonsPageReference
    | JournalEntryReference;
  externalUrl?: string;
  emailAddress?: string;
  phoneNumber?: string;
  openInNewTab?: boolean;
};

export type JournalCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "journalCategory";
};

export type JournalEntry = {
  _id: string;
  _type: "journalEntry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
  };
  categories?: Array<
    {
      _key: string;
    } & JournalCategoryReference
  >;
  author?: string;
  publishedAt?: string;
  updatedAt?: string;
  featured?: boolean;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "lead" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              href?: string;
              openInNewTab?: boolean;
              _type: "link";
              _key: string;
            }
          | {
              vendor?: string;
              url?: string;
              _type: "sourcedFrom";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        size?: "standard" | "wide" | "full";
        _type: "inlineImage";
        _key: string;
      }
    | {
        quote?: string;
        attribution?: string;
        _type: "pullQuote";
        _key: string;
      }
    | {
        beforeImage?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        afterImage?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        caption?: string;
        _type: "beforeAfter";
        _key: string;
      }
    | {
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        itemName?: string;
        vendor?: string;
        price?: string;
        url?: string;
        notes?: string;
        _type: "sourceCard";
        _key: string;
      }
    | {
        label?: string;
        content?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: "bullet";
          markDefs?: Array<{
            href?: string;
            openInNewTab?: boolean;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        _type: "tipCallout";
        _key: string;
      }
    | {
        images?: Array<{
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
          _type: "image";
          _key: string;
        }>;
        layout?: "grid2" | "grid3" | "row";
        caption?: string;
        _type: "imageGallery";
        _key: string;
      }
    | {
        style?: "line" | "ornament" | "space";
        _type: "divider";
        _key: string;
      }
    | {
        url?: string;
        caption?: string;
        _type: "videoEmbed";
        _key: string;
      }
  >;
  seoTitle?: string;
  seoDescription?: string;
  relatedPosts?: Array<
    {
      _key: string;
    } & JournalEntryReference
  >;
};

export type SermonsPage = {
  _id: string;
  _type: "sermonsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  livestreamUrl?: string;
};

export type EventsPage = {
  _id: string;
  _type: "eventsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type JournalPage = {
  _id: string;
  _type: "journalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroScriptAccent?: string;
  stickyCtaLabel?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroScriptAccent?: string;
  formIntroNote?: string;
  formProjectTypeOptions?: Array<string>;
  formLocationOptions?: Array<string>;
  formBudgetOptions?: Array<string>;
  formTimelineOptions?: Array<string>;
  formSourceOptions?: Array<string>;
  whatToExpectEyebrow?: string;
  whatToExpectHeadline?: string;
  whatToExpectContent?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  postInquiryRoadmap?: Array<{
    title?: string;
    body?: string;
    timeEstimate?: string;
    _type: "roadmapStep";
    _key: string;
  }>;
  schedulingLink?: string;
  schedulingLinkLabel?: string;
  availabilityNote?: string;
  note?: string;
};

export type FaqPage = {
  _id: string;
  _type: "faqPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroScriptAccent?: string;
  categoryOrder?: Array<string>;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  secondaryCta?: CtaBlock;
  note?: string;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroScriptAccent?: string;
  storyEyebrow?: string;
  storyHeadline?: string;
  storyContent?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  founderPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  founderAttribution?: string;
  backgroundLine?: string;
  serviceAreaMention?: string;
  philosophyEyebrow?: string;
  philosophyHeadline?: string;
  personalEyebrow?: string;
  personalHeadline?: string;
  personalIntro?: string;
  currentlyList?: Array<{
    label?: string;
    value?: string;
    _type: "currentlyRow";
    _key: string;
  }>;
  rapidFire?: Array<{
    prompt?: string;
    answer?: string;
    _type: "rapidFireRow";
    _key: string;
  }>;
  localSpots?: Array<{
    name?: string;
    note?: string;
    _type: "localSpotRow";
    _key: string;
  }>;
  beyondDesign?: string;
  candidPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  stats?: Array<{
    number?: number;
    suffix?: string;
    label?: string;
    _type: "statItem";
    _key: string;
  }>;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type TestimonialReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "testimonial";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroImages?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  heroPrimaryCta?: CtaBlock;
  heroSecondaryCta?: CtaBlock;
  heroRotatingWords?: Array<string>;
  heroScriptAccent?: string;
  meetFounderPhoto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  meetFounderEyebrow?: string;
  meetFounderHeadline?: string;
  meetFounderContent?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  meetFounderCta?: CtaBlock;
  featuredWorkEyebrow?: string;
  featuredWorkHeadline?: string;
  featuredWorkSubhead?: string;
  featuredWorkCta?: CtaBlock;
  featuredJournalEyebrow?: string;
  featuredJournalHeadline?: string;
  featuredJournalSubhead?: string;
  featuredJournalCta?: CtaBlock;
  processPreviewEyebrow?: string;
  processPreviewHeadline?: string;
  processPreviewSubhead?: string;
  processPreviewCta?: CtaBlock;
  featuredTestimonial?: TestimonialReference;
  testimonialsEyebrow?: string;
  testimonialsHeadline?: string;
  testimonialsScriptAccent?: string;
  testimonialsSubhead?: string;
  testimonialsToShow?: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
  testimonialsAttribution?: string;
  servicesGridEyebrow?: string;
  servicesGridHeadline?: string;
  servicesGridScriptAccent?: string;
  servicesGridSubhead?: string;
  servicesGridCta?: CtaBlock;
  servicesGridFootnote?: string;
  serviceAreaCue?: string;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  attribution?: string;
  date?: string;
  source?: "Facebook" | "Google" | "Houzz" | "Direct (email or text)" | "Other";
  location?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  featured?: boolean;
  sourceType?: "Google" | "Facebook" | "Houzz" | "Direct";
  reviewUrl?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Sermon
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Event
  | JournalCategory
  | PhilosophyPoint
  | FaqItem
  | StudioPlaybook
  | StudioNotes
  | StudioGuide
  | PrivacyPage
  | NotFoundPage
  | SiteSettings
  | HomePageReference
  | AboutPageReference
  | FaqPageReference
  | ContactPageReference
  | JournalPageReference
  | EventsPageReference
  | SermonsPageReference
  | JournalEntryReference
  | CtaBlock
  | JournalCategoryReference
  | JournalEntry
  | SermonsPage
  | EventsPage
  | JournalPage
  | ContactPage
  | FaqPage
  | AboutPage
  | TestimonialReference
  | HomePage
  | Testimonial
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
