/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  sections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & Embed)
  >;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type WorshipResource = {
  _id: string;
  _type: "worshipResource";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  date?: string;
  type?:
    | "Bulletin"
    | "Order of Worship"
    | "Liturgy"
    | "Hymn list"
    | "Newsletter"
    | "Annual report"
    | "Other";
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  externalUrl?: string;
  description?: string;
};

export type Announcement = {
  _id: string;
  _type: "announcement";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  message?: string;
  style?: "info" | "special" | "urgent";
  link?: {
    label?: string;
    url?: string;
  };
  startDate?: string;
  endDate?: string;
  enabled?: boolean;
};

export type Sermon = {
  _id: string;
  _type: "sermon";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  date?: string;
  speaker?: string;
  series?: string;
  scripture?: string;
  videoUrl?: string;
  audioUrl?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h3";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  featured?: boolean;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  eventType?: "recurring" | "oneTime";
  category?:
    | "Worship"
    | "Study"
    | "Meals"
    | "Music"
    | "Fellowship"
    | "Service"
    | "Youth"
    | "Kids"
    | "Outreach"
    | "Special";
  audience?: "Everyone" | "Families" | "Kids" | "Youth" | "Adults" | "Seniors";
  specialService?: boolean;
  liturgicalSeason?:
    | "Advent"
    | "Christmas"
    | "Epiphany"
    | "Lent"
    | "Holy Week"
    | "Easter"
    | "Pentecost"
    | "Ordinary";
  scheduleLabel?: string;
  start?: string;
  end?: string;
  allDay?: boolean;
  location?: string;
  summary?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h3";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  registrationUrl?: string;
  registrationLabel?: string;
  cost?: string;
  contactName?: string;
  contactEmail?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  featured?: boolean;
  featuredOnHome?: boolean;
};

export type MinistryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "ministry";
};

export type Ministry = {
  _id: string;
  _type: "ministry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  audience?:
    | "everyone"
    | "families"
    | "kids"
    | "youth"
    | "adults"
    | "seniors"
    | "neighbors";
  ageRange?: string;
  schedule?: string;
  season?: "Year-round" | "School year" | "Summer" | "Seasonal";
  summary?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  link?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  parentMinistry?: MinistryReference;
  registrationUrl?: string;
  contactName?: string;
  contactEmail?: string;
  displayOrder?: number;
  featured?: boolean;
};

export type StaffMember = {
  _id: string;
  _type: "staffMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  email?: string;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  favorites?: Array<{
    label?: string;
    value?: string;
    _type: "favoriteItem";
    _key: string;
  }>;
  displayOrder?: number;
};

export type FaqItem = {
  _id: string;
  _type: "faqItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h4";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  category?:
    | "Visiting"
    | "Worship"
    | "Kids & Family"
    | "Getting Involved"
    | "Giving"
    | "Weddings & Space";
  displayOrder?: number;
};

export type GivePage = {
  _id: string;
  _type: "givePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & Embed)
  >;
};

export type FormReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "form";
};

export type WeddingsPage = {
  _id: string;
  _type: "weddingsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & Embed)
  >;
  inquiryForm?: FormReference;
};

export type UseOurSpacePage = {
  _id: string;
  _type: "useOurSpacePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & Embed)
  >;
  inquiryForm?: FormReference;
};

export type FoodPage = {
  _id: string;
  _type: "foodPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & Embed)
  >;
};

export type KidsPage = {
  _id: string;
  _type: "kidsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & Embed)
  >;
};

export type ServePage = {
  _id: string;
  _type: "servePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & Embed)
  >;
};

export type GrowPage = {
  _id: string;
  _type: "growPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & Embed)
  >;
};

export type StaffPage = {
  _id: string;
  _type: "staffPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & Embed)
  >;
};

export type MusicPage = {
  _id: string;
  _type: "musicPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & Embed)
  >;
};

export type BeliefsPage = {
  _id: string;
  _type: "beliefsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & Embed)
  >;
};

export type WorshipPage = {
  _id: string;
  _type: "worshipPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & Embed)
  >;
};

export type PrivacyPage = {
  _id: string;
  _type: "privacyPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroScriptAccent?: string;
  lastUpdated?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & Embed)
  >;
};

export type NotFoundPage = {
  _id: string;
  _type: "notFoundPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  eyebrow?: string;
  headline?: string;
  body?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
  };
  primaryCtaLabel?: string;
  primaryCtaHref?: string;
  secondaryCtaLabel?: string;
  secondaryCtaHref?: string;
  tertiaryCtaLabel?: string;
  tertiaryCtaHref?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  tagline?: string;
  mission?: string;
  email?: string;
  phone?: string;
  serviceTimes?: string;
  watchUrl?: string;
  giveUrl?: string;
  appUrl?: string;
  directoryUrl?: string;
  registrationBaseUrl?: string;
  prayerUrl?: string;
  socialInstagram?: string;
  socialFacebook?: string;
  socialYoutube?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  footerCredit?: string;
  footerCreditUrl?: string;
  newsletter?: {
    enabled?: boolean;
    providerLabel?: string;
    formActionUrl?: string;
    audienceId?: string;
    heading?: string;
    blurb?: string;
    buttonLabel?: string;
    successMessage?: string;
    consentNote?: string;
  };
};

export type SectionForm = {
  _type: "sectionForm";
  heading?: string;
  intro?: string;
  form?: FormReference;
};

export type SectionCtaBand = {
  _type: "sectionCtaBand";
  eyebrow?: string;
  headline?: string;
  subhead?: string;
  ctaLabel?: string;
  ctaUrl?: string;
};

export type SectionQuote = {
  _type: "sectionQuote";
  quote?: string;
  attribution?: string;
};

export type SectionCardGrid = {
  _type: "sectionCardGrid";
  eyebrow?: string;
  heading?: string;
  subhead?: string;
  columns?: "2" | "3" | "4";
  cards?: Array<{
    title?: string;
    body?: string;
    link?: string;
    _type: "card";
    _key: string;
  }>;
};

export type SectionImageText = {
  _type: "sectionImageText";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  imageSide?: "left" | "right";
  arched?: boolean;
  eyebrow?: string;
  heading?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h3" | "h4" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  ctaLabel?: string;
  ctaUrl?: string;
};

export type SectionRichText = {
  _type: "sectionRichText";
  eyebrow?: string;
  heading?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h3" | "h4" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  align?: "left" | "center";
};

export type Embed = {
  _type: "embed";
  title?: string;
  mode?: "url" | "html";
  url?: string;
  html?: string;
  aspect?: string;
};

export type HomePageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "homePage";
};

export type AboutPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "aboutPage";
};

export type FaqPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "faqPage";
};

export type ContactPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "contactPage";
};

export type EventsPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "eventsPage";
};

export type SermonsPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sermonsPage";
};

export type CtaBlock = {
  _type: "ctaBlock";
  label?: string;
  linkType?: "internal" | "external" | "email" | "phone";
  internalLink?:
    | HomePageReference
    | AboutPageReference
    | FaqPageReference
    | ContactPageReference
    | EventsPageReference
    | SermonsPageReference;
  externalUrl?: string;
  emailAddress?: string;
  phoneNumber?: string;
  openInNewTab?: boolean;
};

export type SermonsPage = {
  _id: string;
  _type: "sermonsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  livestreamUrl?: string;
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & Embed)
  >;
};

export type EventsPage = {
  _id: string;
  _type: "eventsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & Embed)
  >;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroScriptAccent?: string;
  formIntroNote?: string;
  contactForm?: FormReference;
  whatToExpectEyebrow?: string;
  whatToExpectHeadline?: string;
  whatToExpectContent?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  note?: string;
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & Embed)
  >;
};

export type Form = {
  _id: string;
  _type: "form";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  heading?: string;
  intro?: string;
  mode?: "native" | "embed";
  fields?: Array<{
    label?: string;
    name?: string;
    type?:
      | "text"
      | "email"
      | "tel"
      | "textarea"
      | "select"
      | "checkbox"
      | "date";
    required?: boolean;
    placeholder?: string;
    helpText?: string;
    options?: Array<string>;
    width?: "full" | "half";
    _type: "formField";
    _key: string;
  }>;
  submitLabel?: string;
  successMessage?: string;
  consentNote?: string;
  provider?: {
    service?: "web3forms" | "formspree" | "email";
    accessKey?: string;
    notifyEmail?: string;
  };
  embedUrl?: string;
  embedHtml?: string;
};

export type FaqPage = {
  _id: string;
  _type: "faqPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroScriptAccent?: string;
  categoryOrder?: Array<string>;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  secondaryCta?: CtaBlock;
  note?: string;
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & Embed)
  >;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroScriptAccent?: string;
  storyEyebrow?: string;
  storyHeadline?: string;
  storyContent?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & Embed)
  >;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroKeyword?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroImages?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  heroPrimaryCta?: CtaBlock;
  heroSecondaryCta?: CtaBlock;
  heroRotatingWords?: Array<string>;
  heroScriptAccent?: string;
  seasonalHero?: {
    enabled?: boolean;
    startDate?: string;
    endDate?: string;
    eyebrow?: string;
    headline?: string;
    keyword?: string;
    subhead?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    primaryCtaLabel?: string;
    primaryCtaUrl?: string;
  };
  thisSunday?: {
    enabled?: boolean;
    dateLabel?: string;
    sermonTitle?: string;
    scripture?: string;
    preacher?: string;
    note?: string;
  };
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  welcomeEyebrow?: string;
  welcomeHeadline?: string;
  welcomeBodyP1?: string;
  welcomeBodyP2?: string;
  inclusiveStatement?: string;
  inclusiveBody?: string;
  involvedEyebrow?: string;
  involvedHeadline?: string;
  involvedSubhead?: string;
  recordEyebrow?: string;
  recordHeadline?: string;
  recordBody?: string;
  recordCtaLabel?: string;
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & Embed)
  >;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityFileAssetReference
  | WorshipResource
  | Announcement
  | Sermon
  | Event
  | MinistryReference
  | Ministry
  | StaffMember
  | FaqItem
  | GivePage
  | FormReference
  | WeddingsPage
  | UseOurSpacePage
  | FoodPage
  | KidsPage
  | ServePage
  | GrowPage
  | StaffPage
  | MusicPage
  | BeliefsPage
  | WorshipPage
  | PrivacyPage
  | NotFoundPage
  | SiteSettings
  | SectionForm
  | SectionCtaBand
  | SectionQuote
  | SectionCardGrid
  | SectionImageText
  | SectionRichText
  | Embed
  | HomePageReference
  | AboutPageReference
  | FaqPageReference
  | ContactPageReference
  | EventsPageReference
  | SermonsPageReference
  | CtaBlock
  | SermonsPage
  | EventsPage
  | ContactPage
  | Form
  | FaqPage
  | AboutPage
  | HomePage
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
